### ISSUE TITLE
oc sciencemesh internal server error

### ISSUE THREAD

**Issue by MahdiBaghbani** [pondersource/nc-sciencemesh#267]
the changes done in this commit 8d0c4482bb7bcfacf03f8334bb5e1e38ec45f756 causes OwnCloud to show internal server error.

OwnCloud error message:
```json
{
  "reqId": "9wSFG8zWdqbLrbGNdztp",
  "level": 3,
  "time": "2023-03-28T13:04:39+00:00",
  "remoteAddr": "172.18.0.9",
  "user": "marie",
  "app": "index",
  "method": "GET",
  "url": "/index.php/apps/files/?dir=/&fileid=3",
  "message": "Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer::get()\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\ScienceMesh\\\\AppInfo\\\\ScienceMeshApp->__construct()\\n#1 \\/var\\/www\\/html\\/lib\\/private\\/AppFramework\\/Utility\\/SimpleContainer.php(73): ReflectionClass->newInstanceArgs()\\n#2 \\/var\\/www\\/html\\/lib\\/private\\/AppFramework\\/Utility\\/SimpleContainer.php(89): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass()\\n#3 \\/var\\/www\\/html\\/lib\\/private\\/AppFramework\\/Utility\\/SimpleContainer.php(109): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve()\\n#4 \\/var\\/www\\/html\\/lib\\/private\\/ServerContainer.php(79): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query()\\n#5 \\/var\\/www\\/html\\/apps\\/sciencemesh\\/appinfo\\/app.php(4): OC\\\\ServerContainer->query()\\n#6 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(253): require_once('\\/var\\/www\\/html\\/a...')\\n#7 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(192): OC_App::requireAppFile()\\n#8 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(125): OC_App::loadApp()\\n#9 \\/var\\/www\\/html\\/lib\\/base.php(898): OC_App::loadApps()\\n#10 \\/var\\/www\\/html\\/index.php(54): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\/var\\/www\\/html\\/apps\\/sciencemesh\\/lib\\/AppInfo\\/ScienceMeshApp.php\",\"Line\":27}"
}
```

**Comment by MahdiBaghbani** [comment]
this line should be https://github.com/pondersource/nc-sciencemesh/blob/059b02ba2719f1b9989c86d500485e4f1f35fc7b/lib/AppInfo/ScienceMeshApp.php#L27
```php
$collaboration = $container->query('OCP\Collaboration\Collaborators\ISearch');
```
also `OCP\Collaboration\Collaborators\ISearch` needs to be used.

**Comment by MahdiBaghbani** [comment]
new error message:
```json
{
  "reqId": "u1n3iOE6WrMwp3JhANUl",
  "level": 3,
  "time": "2023-03-28T13:23:14+00:00",
  "remoteAddr": "172.18.0.9",
  "user": "marie",
  "app": "index",
  "method": "GET",
  "url": "/index.php/apps/files/?dir=/&fileid=3",
  "message": "Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCA\\\\ScienceMesh\\\\ScienceMeshProviderFactory' not found\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/lib\\/composer\\/pimple\\/pimple\\/src\\/Pimple\\/Container.php(122): OC\\\\Server->OC\\\\{closure}(*** sensitive parameters replaced ***)\\n#1 \\/var\\/www\\/html\\/lib\\/private\\/AppFramework\\/Utility\\/SimpleContainer.php(107): Pimple\\\\Container->offsetGet()\\n#2 \\/var\\/www\\/html\\/lib\\/private\\/ServerContainer.php(86): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query()\\n#3 \\/var\\/www\\/html\\/lib\\/private\\/Server.php(1656): OC\\\\ServerContainer->query()\\n#4 \\/var\\/www\\/html\\/apps\\/files_sharing\\/lib\\/AppInfo\\/Application.php(165): OC\\\\Server->getShareManager()\\n#5 \\/var\\/www\\/html\\/lib\\/composer\\/pimple\\/pimple\\/src\\/Pimple\\/Container.php(122): OCA\\\\Files_Sharing\\\\AppInfo\\\\Application->OCA\\\\Files_Sharing\\\\AppInfo\\\\{closure}(*** sensitive parameters replaced ***)\\n#6 \\/var\\/www\\/html\\/lib\\/private\\/AppFramework\\/Utility\\/SimpleContainer.php(107): Pimple\\\\Container->offsetGet()\\n#7 \\/var\\/www\\/html\\/apps\\/files_sharing\\/lib\\/AppInfo\\/Application.php(207): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query()\\n#8 \\/var\\/www\\/html\\/apps\\/files_sharing\\/appinfo\\/app.php(38): OCA\\\\Files_Sharing\\\\AppInfo\\\\Application->registerMountProviders()\\n#9 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(253): require_once('\\/var\\/www\\/html\\/a...')\\n#10 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(192): OC_App::requireAppFile()\\n#11 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(125): OC_App::loadApp()\\n#12 \\/var\\/www\\/html\\/lib\\/base.php(898): OC_App::loadApps()\\n#13 \\/var\\/www\\/html\\/index.php(54): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\/var\\/www\\/html\\/lib\\/private\\/Server.php\",\"Line\":898}"
}
```

**Comment by MahdiBaghbani** [comment]
@mrvahedi68 has pointed out the correct way of writing `$container->get`,
get method expects a class not a string.

this bug https://github.com/pondersource/nc-sciencemesh/issues/267#issuecomment-1486886444 still persists.

**Comment by MahdiBaghbani** [comment]
this is fixed in oc-10-take-2 branch.
