### ISSUE TITLE
accept share fails on owncloud

### ISSUE THREAD

**Issue by MahdiBaghbani** [pondersource/nc-sciencemesh#328]
Marek 

```
{"reqId":"CeurWgQMjSqSHDfaEzE5","level":3,"time":"2023-05-26T08:42:49+00:00","remoteAddr":"138.68.152.232","user":"--","app":"PHP","method":"POST","url":"\/index.php\/apps\/sciencemesh\/~einstein\/api\/ocm\/addReceivedShare","message":"Undefined index: resourceId at \/var\/www\/html\/apps\/sciencemesh\/lib\/Controller\/RevaController.php#957"}
{"reqId":"CeurWgQMjSqSHDfaEzE5","level":3,"time":"2023-05-26T08:42:49+00:00","remoteAddr":"138.68.152.232","user":"--","app":"PHP","method":"POST","url":"\/index.php\/apps\/sciencemesh\/~einstein\/api\/ocm\/addReceivedShare","message":"Trying to access array offset on value of type null at \/var\/www\/html\/apps\/sciencemesh\/lib\/Controller\/RevaController.php#957"}
[Fri May 26 08:42:49.732006 2023] [php7:notice] [pid 420] [client 138.68.152.232:58276] RevaController init
[Fri May 26 08:42:49.732040 2023] [php7:notice] [pid 420] [client 138.68.152.232:58276] checkRevadAuth
[Fri May 26 08:42:49.812192 2023] [php7:notice] [pid 420] [client 138.68.152.232:58276] addReceivedShare array (\n  'userId' => 'einstein',\n  '_route' => 'sciencemesh.reva.addReceivedShare',\n  'name' => 'PSNC_logo_biale_.png',\n  'remoteShareId' => '"2"',\n  'grantee' => \n  array (\n    'type' => 'GRANTEE_TYPE_USER',\n    'userId' => \n    array (\n      'idp' => 'https://mesh.pondersource.com/',\n      'opaqueId' => 'einstein',\n    ),\n  ),\n  'owner' => \n  array (\n    'idp' => 'cs3mesh-iop.apps.dcw1.paas.psnc.pl',\n    'opaqueId' => 'sso-0d6c2c87-3da4-44d9-9acd-35a85290992c',\n    'type' => 'USER_TYPE_FEDERATED',\n  ),\n  'creator' => \n  array (\n    'idp' => 'cs3mesh-iop.apps.dcw1.paas.psnc.pl',\n    'opaqueId' => 'sso-0d6c2c87-3da4-44d9-9acd-35a85290992c',\n    'type' => 'USER_TYPE_FEDERATED',\n  ),\n  'ctime' => \n  array (\n    'seconds' => '1685090569',\n  ),\n  'mtime' => \n  array (\n    'seconds' => '1685090569',\n  ),\n  'shareType' => 'SHARE_TYPE_USER',\n  'protocols' => \n  array (\n    0 => \n    array (\n      'webdavOptions' => \n      array (\n        'sharedSecret' => 'f0MC886h0fHMEVselZGFaRHR2QyKD0lU',\n        'permissions' => \n        array (\n          'permissions' => \n          array (\n            'getPath' => true,\n            'initiateFileDownload' => true,\n            'listContainer' => true,\n            'stat' => true,\n          ),\n        ),\n        'uri' => 'cs3mesh-drive.apps.dcw1.paas.psnc.pl/remote.php/dav/ocm/f0MC886h0fHMEVselZGFaRHR2QyKD0lU',\n      ),\n    ),\n    1 => \n    array (\n      'webappOptions' => \n      array (\n        'uriTemplate' => 'https://cernbox.cern.ch/external/sciencemesh/f0MC886h0fHMEVselZGFaRHR2QyKD0lU{relative-path-to-shared-resource}',\n      ),\n    ),\n  ),\n  'state' => 'SHARE_STATE_PENDING',\n  'resourceType' => 'RESOURCE_TYPE_FILE',\n)
[Fri May 26 08:42:49.813140 2023] [php7:notice] [pid 420] [client 138.68.152.232:58276] RevaController init
[Fri May 26 08:42:49.813157 2023] [php7:notice] [pid 420] [client 138.68.152.232:58276] checkRevadAuth
{"reqId":"JcHRHIzc2jWQHKGqaQ7o","level":3,"time":"2023-05-26T08:43:13+00:00","remoteAddr":"192.248.171.117","user":"einstein","app":"no app in context","method":"PROPFIND","url":"\/remote.php\/dav\/files\/einstein\/","message":"Exception: {\"Exception\":\"Sabre\\\\HTTP\\\\ClientHttpException\",\"Message\":\"Unauthorized\",\"Code\":401,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(229): Sabre\\\\HTTP\\\\Client->send()\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(264): Sabre\\\\DAV\\\\Client->propFind()\\n#2 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Storage.php(378): OC\\\\Files\\\\Storage\\\\DAV->propfind()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(637): OCA\\\\Files_Sharing\\\\External\\\\Storage->getPermissions()\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Common->getMetaData()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(459): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Checksum.php(206): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->getMetaData()\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum->getMetaData()\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(115): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(150): OC\\\\Files\\\\Cache\\\\Scanner->getData()\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/View.php(1569): OC\\\\Files\\\\Cache\\\\Scanner->scanFile()\\n#11 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(295): OC\\\\Files\\\\View->getDirectoryContent()\\n#12 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(169): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->handleGetProperties()\\n#14 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1052): Sabre\\\\DAV\\\\Server->emit()\\n#15 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(984): Sabre\\\\DAV\\\\Server->getPropertiesByNode()\\n#16 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1662): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath()\\n#17 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1642): Sabre\\\\DAV\\\\Server->writeMultiStatus()\\n#18 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Sapi.php(83): Sabre\\\\DAV\\\\Server->Sabre\\\\DAV\\\\{closure}(*** sensitive parameters replaced ***)\\n#19 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(490): Sabre\\\\HTTP\\\\Sapi::sendResponse()\\n#20 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#21 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(348): Sabre\\\\DAV\\\\Server->start()\\n#22 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#23 \\\/var\\\/www\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":163}"}
{"reqId":"JcHRHIzc2jWQHKGqaQ7o","level":3,"time":"2023-05-26T08:43:13+00:00","remoteAddr":"192.248.171.117","user":"einstein","app":"files_external","method":"PROPFIND","url":"\/remote.php\/dav\/files\/einstein\/","message":"Unauthorized"}
{"reqId":"6DNYAVX7uXR85sVsKlDv","level":3,"time":"2023-05-26T08:43:18+00:00","remoteAddr":"192.248.171.117","user":"einstein","app":"PHP","method":"POST","url":"\/index.php\/apps\/files_sharing\/api\/externalShares","message":"Undefined index: password at \/var\/www\/html\/apps\/files_sharing\/lib\/External\/Storage.php#92"}
{"reqId":"6DNYAVX7uXR85sVsKlDv","level":3,"time":"2023-05-26T08:43:19+00:00","remoteAddr":"192.248.171.117","user":"einstein","app":"no app in context","method":"POST","url":"\/index.php\/apps\/files_sharing\/api\/externalShares","message":"Exception: {\"Exception\":\"Sabre\\\\HTTP\\\\ClientHttpException\",\"Message\":\"Unauthorized\",\"Code\":401,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(229): Sabre\\\\HTTP\\\\Client->send()\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(264): Sabre\\\\DAV\\\\Client->propFind()\\n#2 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Storage.php(378): OC\\\\Files\\\\Storage\\\\DAV->propfind()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(637): OCA\\\\Files_Sharing\\\\External\\\\Storage->getPermissions()\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Common->getMetaData()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(459): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Checksum.php(206): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->getMetaData()\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum->getMetaData()\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(115): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(150): OC\\\\Files\\\\Cache\\\\Scanner->getData()\\n#10 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Manager.php(212): OC\\\\Files\\\\Cache\\\\Scanner->scanFile()\\n#11 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/Controllers\\\/ExternalSharesController.php(94): OCA\\\\Files_Sharing\\\\External\\\\Manager->getShareFileId()\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OCA\\\\Files_Sharing\\\\Controllers\\\\ExternalSharesController->create()\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#14 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#15 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#16 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#17 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n#18 \\\/var\\\/www\\\/html\\\/index.php(54): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":163}"}
{"reqId":"6DNYAVX7uXR85sVsKlDv","level":3,"time":"2023-05-26T08:43:19+00:00","remoteAddr":"192.248.171.117","user":"einstein","app":"files_external","method":"POST","url":"\/index.php\/apps\/files_sharing\/api\/externalShares","message":"Unauthorized"}
{"reqId":"6DNYAVX7uXR85sVsKlDv","level":3,"time":"2023-05-26T08:43:19+00:00","remoteAddr":"192.248.171.117","user":"einstein","app":"index","method":"POST","url":"\/index.php\/apps\/files_sharing\/api\/externalShares","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageInvalidException\",\"Message\":\"Sabre\\\\HTTP\\\\ClientHttpException: Unauthorized\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(860): OC\\\\Files\\\\Storage\\\\DAV->throwByStatusCode()\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(279): OC\\\\Files\\\\Storage\\\\DAV->convertException()\\n#2 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Storage.php(378): OC\\\\Files\\\\Storage\\\\DAV->propfind()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(637): OCA\\\\Files_Sharing\\\\External\\\\Storage->getPermissions()\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Common->getMetaData()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(459): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Checksum.php(206): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->getMetaData()\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum->getMetaData()\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(115): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(150): OC\\\\Files\\\\Cache\\\\Scanner->getData()\\n#10 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Manager.php(212): OC\\\\Files\\\\Cache\\\\Scanner->scanFile()\\n#11 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/Controllers\\\/ExternalSharesController.php(94): OCA\\\\Files_Sharing\\\\External\\\\Manager->getShareFileId()\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OCA\\\\Files_Sharing\\\\Controllers\\\\ExternalSharesController->create()\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#14 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#15 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#16 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#17 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n#18 \\\/var\\\/www\\\/html\\\/index.php(54): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php\",\"Line\":896}"}

```

![Screenshot from 2023-05-26 12-45-13](https://github.com/pondersource/nc-sciencemesh/assets/13681688/9b81a391-2077-404c-b63d-16a9fcb7dfe5)
![Screenshot from 2023-05-26 12-45-36](https://github.com/pondersource/nc-sciencemesh/assets/13681688/97f7ba01-ee2a-455b-822f-e84abddcdd93)

**Comment by MahdiBaghbani** [comment]
ownCloud maria db:
```
MariaDB [efss]> select * from oc_share;
+----+------------+-----------------------------------------------------------------------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+----------------------------------+-----------+------------+------------+
| id | share_type | share_with                                                                  | uid_owner | uid_initiator | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token                            | mail_send | share_name | attributes |
+----+------------+-----------------------------------------------------------------------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+----------------------------------+-----------+------------+------------+
|  2 |          6 | glopr@sm2.cernbox.cern.ch                                                   | einstein  | einstein      |   NULL | folder    | 13          | NULL        |          13 |             |           1 | 1684434738 |        0 | NULL       | 7DapJKNnf6SRMRO3cz4XAAaQyHCUUsuy |         0 | NULL       | NULL       |
|  3 |          6 | thirsa@surf-iop-rd-app-acc.data.surfsara.nl                                 | einstein  | einstein      |   NULL | folder    | 20          | NULL        |          20 |             |           1 | 1684761116 |        0 | NULL       | lZvFZfarLmHPbUKL581PJ9Ddp10a3bBU |         0 | NULL       | NULL       |
|  4 |          6 | thirsa@surf-iop-rd-app-acc.data.surfsara.nl                                 | einstein  | einstein      |   NULL | folder    | 21          | NULL        |          21 |             |           1 | 1684762472 |        0 | NULL       | gPekRrsBpbRy5K29hkYZwaucLTun2LI0 |         0 | NULL       | NULL       |
|  5 |          6 | thirsa@surf-iop-rd-app-acc.data.surfsara.nl                                 | einstein  | einstein      |   NULL | folder    | 22          | NULL        |          22 |             |           1 | 1684765190 |        0 | NULL       | VVkwDdHWzbrDdotjg3P1aixvKdCu8pUt |         0 | NULL       | NULL       |
|  6 |          6 | thirsa@surf-iop-rd-app-acc.data.surfsara.nl                                 | einstein  | einstein      |   NULL | folder    | 23          | NULL        |          23 |             |           1 | 1684766010 |        0 | NULL       | UTNcoUc6m9ecue4wJCbbNxW5FoeeXaEq |         0 | NULL       | NULL       |
|  7 |          6 | adminDaniel@reva.sciebo.de                                                  | einstein  | einstein      |   NULL | folder    | 34          | NULL        |          34 |             |           1 | 1685090200 |        0 | NULL       | TmcDAJW3QInOZFFpb8WDo2q7ydhqugwF |         0 | NULL       | NULL       |
|  8 |          6 | sso-0d6c2c87-3da4-44d9-9acd-35a85290992c@cs3mesh-iop.apps.dcw1.paas.psnc.pl | einstein  | einstein      |   NULL | folder    | 34          | NULL        |          34 |             |           1 | 1685090232 |        0 | NULL       | 3LLka1ZEJT7EYjwq7J9YGJy7W2p9zCcL |         0 | NULL       | NULL       |
|  9 |          6 | einstein@mesh.pondersource.org                                              | einstein  | einstein      |   NULL | folder    | 39          | NULL        |          39 |             |           1 | 1685093083 |        0 | NULL       | FiKzpQdEZ6BXy8Q9YYDqQIaISNorseGm |         0 | NULL       | NULL       |
+----+------------+-----------------------------------------------------------------------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+----------------------------------+-----------+------------+------------+
8 rows in set (0.000 sec)

```

```
MariaDB [efss]> select * from oc_share_external;
+----+-------------------------------------------------------------+-----------+----------------------------------+----------+-----------------------------+------------------------------------------+----------+------------------------------+----------------------------------+----------+----------+
| id | remote                                                      | remote_id | share_token                      | password | name                        | owner                                    | user     | mountpoint                   | mountpoint_hash                  | accepted | lastscan |
+----+-------------------------------------------------------------+-----------+----------------------------------+----------+-----------------------------+------------------------------------------+----------+------------------------------+----------------------------------+----------+----------+
|  2 | https://mesh.pondersource.org                               |           | ptuKUgULtWBPBLAa051hWUusvB9445j8 |          | qwer                        | einstein                                 | einstein | /qwer                        | a92feb39424232a823dc612969b0ebd5 |        1 |     NULL |
|  3 | https://miskatonic.data.surfsara.nl                         |           | be102NBMB8dBwNAMMxrJiEsYSqVDWJou |          | ShareWithMiroslav2          | thirsa                                   | einstein | /ShareWithMiroslav2          | 10b259bb279d75e846094a29076be1e5 |        1 |     NULL |
|  4 | https://miskatonic.data.surfsara.nl                         |           | ku4v4O696RJtVlMQnFeyzlOEon3cFVtA |          | shareagain                  | thirsa                                   | einstein | /shareagain                  | bed730a5a61bcee5af31e9a56f3ac5d0 |        1 |     NULL |
|  5 | https://cs3mesh-drive.apps.dcw1.paas.psnc.pl/remote.php/dav |           | f0MC886h0fHMEVselZGFaRHR2QyKD0lU |          | PSNC_logo_biale_.png        | sso-0d6c2c87-3da4-44d9-9acd-35a85290992c | einstein | /PSNC_logo_biale_.png        | 086a70b44fab9245ef47fe6623eafae5 |        1 |     NULL |
|  6 | https://mesh.pondersource.org                               |           | swYgWoZ1GjqOpDQCzxWvxtyGg1sejNzm |          | test-ponder-to-ponder       | einstein                                 | einstein | /test-ponder-to-ponder       | cb790216d61ee4db54e3c4db391092f7 |        1 |     NULL |
|  7 | https://cs3mesh-drive.apps.dcw1.paas.psnc.pl/remote.php/dav |           | 5I7bSVvMJ3MaJGgCIhBEeditmmrIEKwM |          | nicolai-kramer-unsplash.jpg | sso-0d6c2c87-3da4-44d9-9acd-35a85290992c | einstein | /nicolai-kramer-unsplash.jpg | ba95714d2a4a441161c3830c72e0b2cb |        1 |     NULL |
+----+-------------------------------------------------------------+-----------+----------------------------------+----------+-----------------------------+------------------------------------------+----------+------------------------------+----------------------------------+----------+----------+
6 rows in set (0.000 sec)

```

Nextcloud maria db:

```
MariaDB [efss]> select * from oc_share;
+----+------------+--------------------------------+----------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+----------------------------------+-----------+------------+------------------+------+---------------+-------+------------+--------------------------+
| id | share_type | share_with                     | password | uid_owner | uid_initiator | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token                            | mail_send | share_name | password_by_talk | note | hide_download | label | attributes | password_expiration_time |
+----+------------+--------------------------------+----------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+----------------------------------+-----------+------------+------------------+------+---------------+-------+------------+--------------------------+
|  1 |          6 | einstein@mesh.pondersource.com | NULL     | einstein  | einstein      |   NULL | folder    | 30          | NULL        |          30 |             |           1 | 1684434521 |        0 | NULL       | G76Go805YLf6AKtKi5RebrVFvzGhX1Ji |         0 | NULL       |                0 | NULL |             0 | NULL  | NULL       | NULL                     |
|  2 |          6 | einstein@mesh.pondersource.com | NULL     | einstein  | einstein      |   NULL | folder    | 34          | NULL        |          34 |             |           1 | 1684434641 |        0 | NULL       | ptuKUgULtWBPBLAa051hWUusvB9445j8 |         0 | NULL       |                0 | NULL |             0 | NULL  | NULL       | NULL                     |
|  3 |          6 | einstein@mesh.pondersource.com | NULL     | einstein  | einstein      |   NULL | folder    | 43          | NULL        |          43 |             |           1 | 1685092487 |        0 | NULL       | swYgWoZ1GjqOpDQCzxWvxtyGg1sejNzm |         0 | NULL       |                0 | NULL |             0 | NULL  | NULL       | NULL                     |
+----+------------+--------------------------------+----------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+----------------------------------+-----------+------------+------------------+------+---------------+-------+------------+--------------------------+
3 rows in set (0.001 sec)

```

```
MariaDB [efss]> select * from oc_share_external;
+----+--------+------------+-------------------------------------------------------------+-----------+----------------------------------+----------+-----------------------------+------------------------------------------+----------+------------------------------+----------------------------------+----------+
| id | parent | share_type | remote                                                      | remote_id | share_token                      | password | name                        | owner                                    | user     | mountpoint                   | mountpoint_hash                  | accepted |
+----+--------+------------+-------------------------------------------------------------+-----------+----------------------------------+----------+-----------------------------+------------------------------------------+----------+------------------------------+----------------------------------+----------+
|  1 |     -1 |          0 | https://mesh.pondersource.com                               |           | mAe9JXMdpA1DjQc1zqJnoVVUbZw96SWm |          | asdf                        | einstein                                 | einstein | /asdf (2)                    | e2117dfb770f1f2d302fe906e0967213 |        1 |
|  2 |     -1 |          0 | https://cs3mesh-drive.apps.dcw1.paas.psnc.pl/remote.php/dav |           | v0hcfpQJQWOvqtNrvTeK1AC1vdgpbOzW |          | PSNC_logo_biale_.png        | sso-0d6c2c87-3da4-44d9-9acd-35a85290992c | einstein | /PSNC_logo_biale_.png        | 086a70b44fab9245ef47fe6623eafae5 |        1 |
|  3 |     -1 |          0 | https://mesh.pondersource.com                               |           | FiKzpQdEZ6BXy8Q9YYDqQIaISNorseGm |          | own-to-next-test            | einstein                                 | einstein | /own-to-next-test            | 16cc812ca6e63df0a061946c2fdec629 |        1 |
|  4 |     -1 |          0 | https://cs3mesh-drive.apps.dcw1.paas.psnc.pl/remote.php/dav |           | XFGsHAvOerLWTmxK3gZADg6X3U5zwBHP |          | nicolai-kramer-unsplash.jpg | sso-0d6c2c87-3da4-44d9-9acd-35a85290992c | einstein | /nicolai-kramer-unsplash.jpg | ba95714d2a4a441161c3830c72e0b2cb |        1 |
+----+--------+------------+-------------------------------------------------------------+-----------+----------------------------------+----------+-----------------------------+------------------------------------------+----------+------------------------------+----------------------------------+----------+
4 rows in set (0.000 sec)
```
